qopnetlabs/qopnet-platform

- apps/qopnet-admin/src/app/pages/suppliers/productSlug.tsx
- Add subname of product
- improve design of supplier product page on dekstop and mobile
> QOP-220 Improve design of supplier product page

- apps/qopnet-api/src/app/suppliers/products/index.ts
- apps/qopnet-api/src/app/suppliers/products/middleware.ts
- Create new API endpoint PUT /suppliers/products/:supplierProductId
> QOP-222 PUT update Supplier Product

- apps/qopnet-api/src/app/business/orders/index.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-api/src/app/suppliers/products/index.ts
- apps/qopnet-api/src/app/suppliers/products/middleware.ts
- Create new API endpoint PATCH /business/orders/:id/confirm
> QOP-238 PATCH confirm payment for business order

- .eslintrc.json
- apps/qopnet-admin/src/app/pages/suppliers.tsx
- apps/qopnet-admin/src/app/pages/suppliers/products.tsx
- libs/qopnet-ui/src/index.ts
- libs/qopnet-ui/src/lib/search-box/search-box.spec.tsx
- libs/qopnet-ui/src/lib/search-box/search-box.tsx
Create a component in a shared UI library via Nx, then use it for:
- All Suppliers
- All Supplier Products
- All Business Orders
```
nx generate @nrwl/react:component search-box --project=qopnet-ui
```
> QOP-242 Reusable UI search box component

- apps/qopnet-api/src/app/business/orders/index.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-api/src/app/payments/records/index.ts
- apps/qopnet-api/src/app/payments/records/middleware.ts
- apps/qopnet-api/src/app/suppliers/products/index.ts
- apps/qopnet-api/src/app/suppliers/products/middleware.ts
Create new API endpoint PATCH `/api/payments/records/proof`
> QOP-236 Patch business order with uploaded receipt image url

- apps/qopnet-commerce/pages/cart/shipment/index.tsx
- add Button "ubah alamat" in checkout/shipment that redirect to /profile
> QOP-230 Button link to edit address in checkout/shipment

- apps/qopnet-api/src/app/business/orders/index.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-api/src/app/payments/records/index.ts
- apps/qopnet-api/src/app/payments/records/middleware.ts
- apps/qopnet-api/src/app/suppliers/products/index.ts
- apps/qopnet-api/src/app/suppliers/products/middleware.ts
- sort the result to ascending
- filter the result where status does not equal "DRAFT"
> QOP-233 My/user's business orders by latest date time first

- apps/qopnet-admin/src/app/components/businessOrderPaymentSection.tsx
- apps/qopnet-admin/src/app/components/businessOrderProductSection.tsx
- apps/qopnet-admin/src/app/components/businessOrderStatusSection.tsx
- apps/qopnet-admin/src/app/pages/businessOrders/businessOrdersParam.tsx
- apps/qopnet-commerce/pages/cart/index.tsx
- Add payment section
- Implement confirm payment
- Refactor business order status section into a component
- Refactor business order product section into a component
- FIx commerce business order status text
> QOP-237 Payment section in business order

- apps/qopnet-commerce/pages/dashboard/orders/index.tsx
- add message "Maaf Anda tidak memiliki daftar pesanan." and button redirect to shop when my order is empty
> QOP-176 Show empty state when my order is empty

- apps/qopnet-commerce/pages/[supplierParam]/index.tsx
- apps/qopnet-commerce/pages/[supplierParam]/orders/index.tsx
- Terdapat X produk
- Show ? when no address
- Button to Orders for specific supplier /supplier-name/orders
- Some texts related to the Supplier name
> QOP-228 Improve supplier page information

- apps/qopnet-commerce/components/breadcrumb.tsx
- apps/qopnet-commerce/pages/cart/payment/index.tsx
Remove the "Orders" link in the checkout process.
> QOP-249 Remove Orders breadcrumb in checkout process

- apps/qopnet-commerce/pages/cart/payment/index.tsx
- apps/qopnet-commerce/pages/cart/shipment/index.tsx
smaller the button of "Ubah Alamat" in cart
> QOP-256 Change button size in cart

- apps/qopnet-commerce/pages/dashboard/orders/index.tsx
- libs/qopnet-ui/src/lib/supplier-product/supplier-product.tsx
- Replace \n with <br/>
- Fix status text in commerce dashboard
> QOP-182 Commerce product description display new line

- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-commerce/pages/cart/payment/index.tsx
- apps/qopnet-commerce/pages/dashboard/orders/[businessOrderParam]/index.tsx
- New single business order page
- New business order payment section
> QOP-258 Single business order page after checkout process with payment section

- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-api/src/app/payments/va/middleware.ts
1. getbill
- validate virtual account number by latest order and status is "WAITING_FOR_PAYMENT"
2. paybill
- check virtual account number where totalBillPayment is BILL_AMOUNT and status is "WAITING_FOR_PAYMENT"
- update bussiness order status to "PAID"
- update payment record to "PAID"
3. revbill
- check virtual account number where totalBillPayment is BILL_AMOUNT and status is "WAITING_FOR_PAYMENT"
- update bussiness order status to "REFUNDED"
- update payment record to "CANCELED"
> QOP-264 Improve getbill, paybill, and revbill

- apps/qopnet-api/src/app/business/orders/index.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
Create new api endpoint get all the BusinessOrderItem by Supplier that already paid only
`GET /api/business/orders/items/paid/supplierHandle`
> QOP-255 GET all BusinessOrderItem by Supplier that already paid

- apps/qopnet-api/src/app/business/orders/middleware.ts
businessOrder:
- owner
- shipmentAddress
- shipmentCourier
> QOP-269 Add more detail response get all paid business order items by supplier

- prisma/data/couriers.json
- prisma/migrations/20211111045109_create_status_to_business_order_item/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- adjust data couriers json
- disable seed courier vehicles
> QOP-270 Courier options only deliveree and kurir toko sendiri

- apps/qopnet-api/src/app/business/orders/index.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
`/api/business/orders/items/paid/:supplierSlug/:businessOrderItemId`
> QOP-274 API get one paid business order item by supplier

- apps/qopnet-api/src/app/suppliers/middleware.ts
- prisma/migrations/20211114064510_m2m_couriers_on_supplier_products/migration.sql
- prisma/schema.prisma
Prisma many to many relationships between Courier and SupplierProduct
Create supplier product include couriers array
> QOP-279 Supplier product can manage couriers

- apps/qopnet-api/src/app/suppliers/middleware.ts
- libs/shared-types/src/lib/shared-types.ts
- package.json
- prisma/data/supplier-products-anekabusa.json
- prisma/seed.ts
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#remarks-9
- Use Foreach 
- CreateMany can't connect relation
> QOP-280 Seed couriers into supplier products

- apps/qopnet-api/src/app/suppliers/products/middleware.ts
- apps/qopnet-commerce/components/supplier-product.tsx
- apps/qopnet-commerce/pages/[supplierParam]/[supplierProductParam]/edit-supplier-product/index.tsx
1. Fetch all available couriers
2. Onclick courier put the id into React Hook Form as an array of string
3. Include validation with required
4. Submit the form as usual
> QOP-281 Commerce create supplier product form with couriers

- apps/qopnet-api/src/app/addresses/middleware.ts
- apps/qopnet-api/src/app/business/orders/middleware.ts
- apps/qopnet-api/src/app/couriers/middleware.ts
- apps/qopnet-api/src/app/couriers/vehicles/middleware.ts
- apps/qopnet-api/src/app/merchants/middleware.ts
- apps/qopnet-api/src/app/payments/records/middleware.ts
- apps/qopnet-api/src/app/promos/submissions/middleware.ts
- apps/qopnet-api/src/app/suppliers/middleware.ts
- apps/qopnet-api/src/app/users/middleware.ts
- address
- business orders
- my bussiness orders
- paid business order items
- couriers
- courier vehicles
- merchants
- payment records
- profiles
- suppliers
- supplier products
- users
> QOP-278 API sort by desc updatedAt

- prisma/data/addresses.json
- prisma/seed.ts
1. add supplierId on addresses.json
2. move seed order (seed addresses after seed suppliers complete)
3. clear _couriers_on_supplier_products table
> QOP-283 Fix Supplier's address in seed data
